- name: install & run nginx
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  
  - name: running  nginx
    ansible.builtin.service:
     name: nginx
     state: installed
     enabled: yes
  

  