- name: play with varivbles
  hosts: local
  connection: local
  vars:
    course: ANSIBLE
    hours: 10HRS
    Trainer: SIVAKUMAR
  tasks:
  - name: print course information
    ansible.buildin.debug:
      msg: "Hi Folks!, {{ course }} for {{ hours }} Trainer is {{ Trainer }}"
  - name: print course information again
    ansible.builtin.debug:
    
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"