- name: users from inventory
  hosts: local
  connection: local
  tasks:
  - name: course details from inventory
    ansible.buildin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"
