- name: install nginx based linux flavours
  hosts: frontend
  tasks:
  - name: install nginx if it is redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
      
    when: ansible_os_family == "RedHat"
  tasks:  
  - name: install nginx if it is redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
      
    when: ansible_os_family == "Debian"
    
