- name: loops
  hosts: local
  connection: local
  tasks:
  - name: loops in ansible
    ansible.builtin.debug:
      msg: "Today's Menu :: , {{ item }}"
    loop:
    - idly
    - dosa
    - puri
    - upma