- name: install different packages
  host: frontend
  tasks:
  - name: installing mysql nginx nodejs
    ansible.builtin.dnf:
      name: " {{ item }} "
      state: installed
    loop:
    - mysql
    - nodejs
    - nginx
    - zip