- name: install different packages
  hosts: frontend
  become: yes
  tasks:
  - name: installing mysql nginx nodejs
    ansible.builtin.dnf:
      name: " {{ item.name }} "
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql' , state: 'present' }
    - { name: 'zip' , state: 'present' }