- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: Sivakumar
  tasks:
    - name: print course information
      vars:
        COURSE: DevOps
      ansible.buildin.debug:
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"
  tasks:
    - name: print course information again
      ansible.buildin.debug:
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"